### ISSUE TITLE
String min max lengths not reflected after edit

### ISSUE THREAD

**Issue by TharinduAmila** [jackwootton/json-schema-public#1]
at current https://jsonschema.net/#/ string min max lengths not reflected after edit

**Comment by TharinduAmila** [comment]
Thanks for the label. It seems string regex is also not reflected.

**Comment by LorenzoRogai** [comment]
Can confirm this too, i can't these three options being applied to the schema after saving

**Comment by jackwootton** [comment]
Quick update. This is fixed in UAT and should land this weekend. Thanks for your patience.

**Comment by jackwootton** [comment]
This should be fixed now.
